# fly.toml app configuration file generated for api-dindin on 2023-11-01T14:53:20-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-dindin"
primary_region = "gru"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
